### PR TITLE
feat: pick bug fix from v1.x

### PR DESCRIPTION
**Pull request by fengmk2**
v1: 1.20.1
    
closes https://github.com/sofastack/sofa-rpc-node/issues/88

### CODE REVIEW

**Comment by fengmk2** [comment]
我来合并。

**Comment by fengmk2** [comment]
还需要增加 github action

**Comment by fengmk2** [comment]
@killagu @gxcsoccer npm owner 加一下我

**Review by mansonchor — APPROVED** [review]
+1

**Comment by mansonchor** [comment]
> @killagu @gxcsoccer npm owner 加一下我

npm owner add fengmk2
+ fengmk2 (sofa-rpc-node)

**Comment by fengmk2** [comment]
2.1.0

**Pull request merged**
